apiVersion: apps/v1
kind: Deployment
metadata:
  name: streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming
  template:
    metadata:
      labels:
        app: streaming
    spec:
      containers:
      - name: streaming
        image: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-streaming:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: streaming
spec:
  type: ClusterIP
  selector:
    app: streaming
  ports:
  - port: 3002
    targetPort: 3002
