replicaCount: 1

images:
  frontend:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-frontend
    tag: latest
  auth:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-auth
    tag: latest
  streaming:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-streaming
    tag: latest
  admin:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-admin
    tag: latest
  chat:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-chat
    tag: latest

ports:
  frontend: 80
  auth: 3001
  streaming: 3002
  admin: 3003
  chat: 3004
