replicaCount: 1
jwtSecret: "mysecretkey123"
images:
  frontend:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-frontend
    tag: latest
  auth:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-auth
    tag: latest
  streaming:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-streaming
    tag: latest
  admin:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-admin
    tag: latest
  chat:
    repository: 640928554403.dkr.ecr.us-east-1.amazonaws.com/streamingapp-chat
    tag: latest
mongoUri: "mongodb+srv://stream:Stream123@streamingapp.1jjw3rq.mongodb.net/streamingapp?retryWrites=true&w=majority"
